import json
import unittest

import app as app_module

json_data = '''
{
  "version": 2,
  "workbook": "异环云配队.xlsx",
  "slotCount": 21,
  "team": {
    "roles": [
      "娜娜莉",
      "主角",
      "阿德勒",
      "九原"
    ],
    "repeats": [
      1,
      0.667,
      1,
      0.75,
      2,
      0.75,
      3,
      1.5,
      0.5,
      0.5,
      1,
      1,
      1,
      1,
      12,
      1,
      1,
      1,
      12,
      1.5,
      null
    ],
    "actions": [
      [
        null,
        null,
        "e",
        "q",
        "5a",
        "5a副手",
        "闪反",
        "闪反副手",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "C觉追击",
        null,
        null
      ],
      [
        "e",
        "q",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "援护",
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "q",
        "dot10跳",
        "e",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "q清算",
        "6枪",
        "e",
        "dot",
        "援护",
        "q",
        "清算",
        null,
        null,
        null
      ]
    ],
    "buffs": {
      "14": [
        null,
        null,
        "娜娜莉E暴伤",
        "娜娜莉E暴伤",
        "娜娜莉E暴伤",
        "娜娜莉E暴伤",
        "娜娜莉E暴伤",
        "娜娜莉E暴伤",
        null,
        "阿德勒6命Q后E",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "15": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "阿德勒6命Q后E",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "16": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "17": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "18": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "19": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "20": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "21": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "22": [
        "光套减防",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "光套减防",
        null
      ],
      "23": [
        "音速蓝刺猬",
        "音速蓝刺猬",
        "音速蓝刺猬",
        "音速蓝刺猬",
        "音速蓝刺猬",
        "音速蓝刺猬",
        "音速蓝刺猬",
        "音速蓝刺猬",
        "音速蓝刺猬",
        "音速蓝刺猬",
        "音速蓝刺猬",
        "音速蓝刺猬",
        "音速蓝刺猬",
        "音速蓝刺猬",
        "音速蓝刺猬",
        "音速蓝刺猬",
        "音速蓝刺猬",
        "音速蓝刺猬",
        "音速蓝刺猬",
        "音速蓝刺猬",
        null
      ],
      "24": [
        null,
        "光套减防",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "25": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "26": [
        null,
        null,
        null,
        "预备备开Q非普攻",
        null,
        "预备备开Q普攻",
        null,
        "预备备开Q普攻",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "27": [
        null,
        null,
        null,
        null,
        "预备备开Q普攻",
        null,
        "预备备开Q非普攻",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "预备备开Q非普攻",
        null,
        null
      ],
      "28": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "29": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    },
    "misc": {
      "F9": 80,
      "G9": 82,
      "H9": 70,
      "F11": 0.2,
      "H11": 0.2,
      "G11": null,
      "G13": "BOSS",
      "H13": null,
      "AD13": 16
    }
  },
  "gear": {
    "主角": {
      "V": "休息日",
      "X": "失落光芒",
      "Z": 10,
      "AB": "精通",
      "AC": 10,
      "AD": "攻击",
      "AF": 6,
      "AG": 0.15,
      "AH": 0.1,
      "AI": 0.2,
      "AJ": 90,
      "AK": null,
      "AL": 0.125,
      "AM": null,
      "AN": null,
      "AO": null,
      "AP": null,
      "AQ": null,
      "AR": null,
      "AS": true,
      "AT": true,
      "AU": true,
      "AV": null,
      "AW": null
    },
    "浔": {
      "V": "行进于时间之外",
      "X": "失落光芒",
      "Z": 10,
      "AB": "暴击",
      "AC": 10,
      "AD": "属伤",
      "AF": 4,
      "AG": 0.15,
      "AH": 0.15,
      "AI": 0.3,
      "AJ": null,
      "AK": null,
      "AL": 0.1875,
      "AM": null,
      "AN": null,
      "AO": null,
      "AP": null,
      "AQ": null,
      "AR": null,
      "AS": null,
      "AT": null,
      "AU": null,
      "AV": null,
      "AW": null
    },
    "小吱": {
      "V": "思考喵",
      "X": "失落光芒",
      "Z": 10,
      "AB": "暴击",
      "AC": 10,
      "AD": "属伤",
      "AF": 4,
      "AG": 0.15,
      "AH": 0.15,
      "AI": 0.3,
      "AJ": null,
      "AK": null,
      "AL": 0.1875,
      "AM": null,
      "AN": null,
      "AO": null,
      "AP": null,
      "AQ": null,
      "AR": true,
      "AS": null,
      "AT": null,
      "AU": null,
      "AV": null,
      "AW": true
    },
    "埃德嘉": {
      "V": "扭曲之城的呼唤",
      "X": "缇娅的夜间酒馆",
      "Z": 10,
      "AB": "治疗",
      "AC": 10,
      "AD": "生命",
      "AF": 6,
      "AG": 0.15,
      "AH": 0.15,
      "AI": 0.3,
      "AJ": null,
      "AK": null,
      "AL": null,
      "AM": null,
      "AN": 0.1875,
      "AO": null,
      "AP": null,
      "AQ": null,
      "AR": true,
      "AS": true,
      "AT": true,
      "AU": true,
      "AV": true,
      "AW": true
    },
    "娜娜莉": {
      "V": "预备备",
      "X": "森林萤火之心",
      "Z": 10,
      "AB": "属伤",
      "AC": 5,
      "AD": "暴击",
      "AF": 5,
      "AG": 0.15,
      "AH": 0.15,
      "AI": 0.3,
      "AJ": null,
      "AK": null,
      "AL": 0.1875,
      "AM": null,
      "AN": null,
      "AO": null,
      "AP": null,
      "AQ": null,
      "AR": null,
      "AS": null,
      "AT": null,
      "AU": null,
      "AV": null,
      "AW": null
    },
    "九原": {
      "V": "现实避难所",
      "X": "森林萤火之心",
      "Z": 10,
      "AB": "暴击",
      "AC": 5,
      "AD": "暴击",
      "AF": 5,
      "AG": 0.15,
      "AH": 0.15,
      "AI": 0.3,
      "AJ": null,
      "AK": null,
      "AL": 0.1875,
      "AM": null,
      "AN": null,
      "AO": null,
      "AP": null,
      "AQ": null,
      "AR": null,
      "AS": true,
      "AT": null,
      "AU": null,
      "AV": null,
      "AW": null
    },
    "薄荷": {
      "V": "开始净空",
      "X": "森林萤火之心",
      "Z": 10,
      "AB": "属伤",
      "AC": 8,
      "AD": "暴击",
      "AF": 4,
      "AG": 0.15,
      "AH": 0.15,
      "AI": 0.3,
      "AJ": null,
      "AK": null,
      "AL": 0.1875,
      "AM": null,
      "AN": null,
      "AO": null,
      "AP": null,
      "AQ": null,
      "AR": true,
      "AS": true,
      "AT": true,
      "AU": true,
      "AV": true,
      "AW": true
    },
    "白藏": {
      "V": "茶花会",
      "X": "真红：双生蝶",
      "Z": 10,
      "AB": "属伤",
      "AC": 8,
      "AD": "暴击",
      "AF": 4,
      "AG": 0.15,
      "AH": 0.15,
      "AI": 0.3,
      "AJ": null,
      "AK": null,
      "AL": 0.1875,
      "AM": null,
      "AN": null,
      "AO": null,
      "AP": null,
      "AQ": null,
      "AR": null,
      "AS": null,
      "AT": null,
      "AU": null,
      "AV": null,
      "AW": null
    },
    "早雾": {
      "V": "好狗狗走四方",
      "X": "音速蓝刺猬",
      "Z": 10,
      "AB": "精通",
      "AC": 8,
      "AD": "属伤",
      "AF": 6,
      "AG": 0.15,
      "AH": 0.1,
      "AI": 0.2,
      "AJ": 90,
      "AK": null,
      "AL": 0.125,
      "AM": null,
      "AN": null,
      "AO": null,
      "AP": null,
      "AQ": null,
      "AR": null,
      "AS": null,
      "AT": null,
      "AU": null,
      "AV": null,
      "AW": null
    },
    "阿德勒": {
      "V": "勿忘伞",
      "X": "守卫王国",
      "Z": 10,
      "AB": "属伤",
      "AC": 12,
      "AD": "防御",
      "AF": 6,
      "AG": 0.15,
      "AH": 0.15,
      "AI": 0.3,
      "AJ": null,
      "AK": null,
      "AL": null,
      "AM": null,
      "AN": null,
      "AO": null,
      "AP": 0.2625,
      "AQ": null,
      "AR": true,
      "AS": true,
      "AT": true,
      "AU": true,
      "AV": true,
      "AW": true
    },
    "安魂曲": {
      "V": "「最后一朵玫瑰」",
      "X": "迪亚波罗斯",
      "Z": 10,
      "AB": "属伤",
      "AC": 10,
      "AD": "属伤",
      "AF": 4,
      "AG": 0.15,
      "AH": 0.1,
      "AI": 0.3,
      "AJ": null,
      "AK": null,
      "AL": 0.1875,
      "AM": null,
      "AN": null,
      "AO": null,
      "AP": null,
      "AQ": null,
      "AR": null,
      "AS": null,
      "AT": null,
      "AU": null,
      "AV": null,
      "AW": true
    },
    "达芙蒂尔": {
      "V": "漆黑青春妄想",
      "X": "迪亚波罗斯",
      "Z": 10,
      "AB": "属伤",
      "AC": 10,
      "AD": "属伤",
      "AF": 4,
      "AG": 0.15,
      "AH": 0.1,
      "AI": 0.2,
      "AJ": 30,
      "AK": 60,
      "AL": 0.125,
      "AM": null,
      "AN": null,
      "AO": null,
      "AP": null,
      "AQ": null,
      "AR": null,
      "AS": null,
      "AT": true,
      "AU": null,
      "AV": null,
      "AW": null
    },
    "法帝娅": {
      "V": "永恒圆舞曲",
      "X": "音速蓝刺猬",
      "Z": 10,
      "AB": "倾陷",
      "AC": 6,
      "AD": "生命",
      "AF": 6,
      "AG": 0.15,
      "AH": 0.1,
      "AI": 0.2,
      "AJ": null,
      "AK": 90,
      "AL": null,
      "AM": null,
      "AN": 0.125,
      "AO": null,
      "AP": null,
      "AQ": null,
      "AR": null,
      "AS": null,
      "AT": null,
      "AU": null,
      "AV": null,
      "AW": null
    },
    "哈尼娅": {
      "V": "引爆全场",
      "X": "音速蓝刺猬",
      "Z": 10,
      "AB": "倾陷",
      "AC": 10,
      "AD": "攻击",
      "AF": 6,
      "AG": 0.15,
      "AH": 0.1,
      "AI": 0.2,
      "AJ": null,
      "AK": 90,
      "AL": 0.125,
      "AM": null,
      "AN": null,
      "AO": null,
      "AP": null,
      "AQ": null,
      "AR": true,
      "AS": true,
      "AT": true,
      "AU": true,
      "AV": true,
      "AW": true
    },
    "哈索尔": {
      "V": "焰魂狂飙",
      "X": "街头拳王",
      "Z": 10,
      "AB": "暴击",
      "AC": 10,
      "AD": "攻击",
      "AF": 4,
      "AG": 0.15,
      "AH": 0.15,
      "AI": 0.3,
      "AJ": null,
      "AK": null,
      "AL": 0.1875,
      "AM": null,
      "AN": null,
      "AO": null,
      "AP": null,
      "AQ": null,
      "AR": null,
      "AS": null,
      "AT": null,
      "AU": null,
      "AV": null,
      "AW": null
    },
    "翳": {
      "V": "当心头顶",
      "X": "街头拳王",
      "Z": 10,
      "AB": "暴击",
      "AC": 10,
      "AD": "攻击",
      "AF": 4,
      "AG": 0.15,
      "AH": 0.15,
      "AI": 0.3,
      "AJ": null,
      "AK": null,
      "AL": 0.1875,
      "AM": null,
      "AN": null,
      "AO": null,
      "AP": null,
      "AQ": null,
      "AR": true,
      "AS": true,
      "AT": true,
      "AU": true,
      "AV": true,
      "AW": true
    }
  }
}
'''

class CloudTeamCalculateTests(unittest.TestCase):
    def setUp(self):
        app_module.app.testing = True
        self.client = app_module.app.test_client()

    def test_calculate_single_dataset_total_damage_is_expected(self):
        payload = json.loads(json_data)
        resp = self.client.post("/api/cloud-team/calculate", json=payload)
        print(resp.get_data(as_text=True))
        self.assertEqual(resp.status_code, 200)
        data = resp.get_json()
        total_damage = data["summary"]["totalDamage"]
        self.assertAlmostEqual(total_damage, 719149, delta=1)
